# Generated by Django 5.1.5 on 2025-02-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
