# Generated by Django 5.1.5 on 2025-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='estado',
        ),
        migrations.AddField(
            model_name='doacao',
            name='estado_conservacao',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Bom', 'Bom'), ('Ruim', 'Ruim')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
